apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homer
  namespace: argocd
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    repoURL: git@github.com:kr1ps/kube-homer.git
    targetRevision: HEAD
    path: ./helm
    helm:
      releaseName: homer
      valueFiles:
      - values-homer.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: homer